levels = [
    {
        "name": "第零关：指法练习",
        "maxTime": 120,
        "condition": 1.0,
        "data": [
            {"display": "a"},
            {"display": "b"},
            {"display": "c"},
            {"display": "d"},
            {"display": "e"},
            {"display": "f"},
            {"display": "g"},
            {"display": "h"},
            {"display": "i"},
            {"display": "j"},
            {"display": "k"},
            {"display": "l"},
            {"display": "m"},
            {"display": "n"},
            {"display": "o"},
            {"display": "p"},
            {"display": "q"},
            {"display": "r"},
            {"display": "s"},
            {"display": "t"},
            {"display": "u"},
            {"display": "v"},
            {"display": "w"},
            {"display": "x"},
            {"display": "y"},
            {"display": "z"}
        ]
    },
    {
        "name": "第一关：字根输入",
        "maxTime": 120,
        "condition": 1.2,
        "data": [
            {'target': 'g', 'display': '一'},
            {'target': 'g', 'display': '丁'},
            {'target': 'g', 'display': '丂'},
            {'target': 'g', 'display': '七'},
            {'target': 'g', 'display': '丄'},
            {'target': 'g', 'display': '丅'},
            {'target': 'f', 'display': '丐'},
            {'target': 'f', 'display': '丑'},
            {'target': 'f', 'display': '丒'},
            {'target': 'f', 'display': '专'},
            {'target': 'f', 'display': '且'},
            {'target': 'f', 'display': '丕'},
            {'target': 'f', 'display': '世'},
            {'target': 'f', 'display': '丗'},
            {'target': 'f', 'display': '丘'},
            {'target': 'f', 'display': '丙'},
            {'target': 'd', 'display': '丠'},
            {'target': 'd', 'display': '両'},
            {'target': 'd', 'display': '丢'},
            {'target': 'd', 'display': '丣'},
            {'target': 'd', 'display': '两'},
            {'target': 'd', 'display': '严'},
            {'target': 'd', 'display': '並'},
            {'target': 'd', 'display': '丧'},
            {'target': 'd', 'display': '丨'},
            {'target': 'd', 'display': '丩'},
            {'target': 'd', 'display': '个'},
            {'target': 'd', 'display': '丫'},
            {'target': 's', 'display': '丰'},
            {'target': 's', 'display': '丱'},
            {'target': 's', 'display': '串'},
            {'target': 's', 'display': '丳'},
            {'target': 'a', 'display': '乀'},
            {'target': 'a', 'display': '乁'},
            {'target': 'a', 'display': '乂'},
            {'target': 'a', 'display': '乃'},
            {'target': 'a', 'display': '乄'},
            {'target': 'a', 'display': '久'},
            {'target': 'a', 'display': '乆'},
            {'target': 'a', 'display': '乇'},
            {'target': 'a', 'display': '么'},
            {'target': 'a', 'display': '义'},
            {'target': 'a', 'display': '乊'},
            {'target': 'a', 'display': '之'},
            {'target': 'a', 'display': '乌'},
            {'target': 'a', 'display': '乍'},
            {'target': 'h', 'display': '乐'},
            {'target': 'h', 'display': '乑'},
            {'target': 'h', 'display': '乒'},
            {'target': 'h', 'display': '乓'},
            {'target': 'h', 'display': '乔'},
            {'target': 'h', 'display': '乕'},
            {'target': 'h', 'display': '乖'},
            {'target': 'h', 'display': '乗'},
            {'target': 'h', 'display': '乘'},
            {'target': 'h', 'display': '乙'},
            {'target': 'h', 'display': '乚'},
            {'target': 'j', 'display': '习'},
            {'target': 'j', 'display': '乡'},
            {'target': 'j', 'display': '乢'},
            {'target': 'j', 'display': '乣'},
            {'target': 'j', 'display': '乤'},
            {'target': 'j', 'display': '乥'},
            {'target': 'j', 'display': '书'},
            {'target': 'j', 'display': '乧'},
            {'target': 'j', 'display': '乨'},
            {'target': 'k', 'display': '买'},
            {'target': 'k', 'display': '乱'},
            {'target': 'k', 'display': '乲'},
            {'target': 'l', 'display': '亀'},
            {'target': 'l', 'display': '亁'},
            {'target': 'l', 'display': '亂'},
            {'target': 'l', 'display': '亃'},
            {'target': 'l', 'display': '亄'},
            {'target': 'l', 'display': '亅'},
            {'target': 'l', 'display': '了'},
            {'target': 'l', 'display': '亇'},
            {'target': 'l', 'display': '予'},
            {'target': 'l', 'display': '争'},
            {'target': 'l', 'display': '亊'},
            {'target': 'm', 'display': '亐'},
            {'target': 'm', 'display': '云'},
            {'target': 'm', 'display': '互'},
            {'target': 'm', 'display': '亓'},
            {'target': 'm', 'display': '五'},
            {'target': 'm', 'display': '井'},
            {'target': 'm', 'display': '亖'},
            {'target': 'm', 'display': '亗'},
            {'target': 't', 'display': '亠'},
            {'target': 't', 'display': '亡'},
            {'target': 't', 'display': '亢'},
            {'target': 't', 'display': '亣'},
            {'target': 't', 'display': '交'},
            {'target': 't', 'display': '亥'},
            {'target': 't', 'display': '亦'},
            {'target': 't', 'display': '产'},
            {'target': 't', 'display': '亨'},
            {'target': 'r', 'display': '亰'},
            {'target': 'r', 'display': '亱'},
            {'target': 'r', 'display': '亲'},
            {'target': 'r', 'display': '亳'},
            {'target': 'r', 'display': '亴'},
            {'target': 'r', 'display': '亵'},
            {'target': 'r', 'display': '亶'},
            {'target': 'r', 'display': '亷'},
            {'target': 'r', 'display': '亸'},
            {'target': 'r', 'display': '亹'},
            {'target': 'e', 'display': '什'},
            {'target': 'e', 'display': '仁'},
            {'target': 'e', 'display': '仂'},
            {'target': 'e', 'display': '仃'},
            {'target': 'e', 'display': '仄'},
            {'target': 'e', 'display': '仅'},
            {'target': 'e', 'display': '仆'},
            {'target': 'e', 'display': '仇'},
            {'target': 'e', 'display': '仈'},
            {'target': 'e', 'display': '仉'},
            {'target': 'e', 'display': '今'},
            {'target': 'e', 'display': '介'},
            {'target': 'e', 'display': '仌'},
            {'target': 'w', 'display': '仐'},
            {'target': 'w', 'display': '仑'},
            {'target': 'w', 'display': '仒'},
            {'target': 'w', 'display': '仓'},
            {'target': 'w', 'display': '仔'},
            {'target': 'q', 'display': '仠'},
            {'target': 'q', 'display': '仡'},
            {'target': 'q', 'display': '仢'},
            {'target': 'q', 'display': '代'},
            {'target': 'q', 'display': '令'},
            {'target': 'q', 'display': '以'},
            {'target': 'q', 'display': '仦'},
            {'target': 'q', 'display': '仧'},
            {'target': 'q', 'display': '仨'},
            {'target': 'q', 'display': '仩'},
            {'target': 'q', 'display': '仪'},
            {'target': 'q', 'display': '仫'},
            {'target': 'q', 'display': '们'},
            {'target': 'q', 'display': '仭'},
            {'target': 'q', 'display': '仮'},
            {'target': 'y', 'display': '仰'},
            {'target': 'y', 'display': '仱'},
            {'target': 'y', 'display': '仲'},
            {'target': 'y', 'display': '仳'},
            {'target': 'y', 'display': '仴'},
            {'target': 'y', 'display': '仵'},
            {'target': 'y', 'display': '件'},
            {'target': 'y', 'display': '价'},
            {'target': 'y', 'display': '仸'},
            {'target': 'y', 'display': '仹'},
            {'target': 'u', 'display': '伀'},
            {'target': 'u', 'display': '企'},
            {'target': 'u', 'display': '伂'},
            {'target': 'u', 'display': '伃'},
            {'target': 'u', 'display': '伄'},
            {'target': 'u', 'display': '伅'},
            {'target': 'u', 'display': '伆'},
            {'target': 'u', 'display': '伇'},
            {'target': 'u', 'display': '伈'},
            {'target': 'u', 'display': '伉'},
            {'target': 'u', 'display': '伊'},
            {'target': 'u', 'display': '伋'},
            {'target': 'u', 'display': '伌'},
            {'target': 'i', 'display': '伐'},
            {'target': 'i', 'display': '休'},
            {'target': 'i', 'display': '伒'},
            {'target': 'i', 'display': '伓'},
            {'target': 'i', 'display': '伔'},
            {'target': 'i', 'display': '伕'},
            {'target': 'i', 'display': '伖'},
            {'target': 'i', 'display': '众'},
            {'target': 'i', 'display': '优'},
            {'target': 'i', 'display': '伙'},
            {'target': 'i', 'display': '会'},
            {'target': 'p', 'display': '估'},
            {'target': 'p', 'display': '伱'},
            {'target': 'p', 'display': '伲'},
            {'target': 'p', 'display': '伳'},
            {'target': 'p', 'display': '伴'},
            {'target': 'p', 'display': '伵'},
            {'target': 'n', 'display': '佀'},
            {'target': 'n', 'display': '佁'},
            {'target': 'n', 'display': '佂'},
            {'target': 'n', 'display': '佃'},
            {'target': 'n', 'display': '佄'},
            {'target': 'n', 'display': '佅'},
            {'target': 'n', 'display': '但'},
            {'target': 'n', 'display': '佇'},
            {'target': 'n', 'display': '佈'},
            {'target': 'n', 'display': '佉'},
            {'target': 'n', 'display': '佊'},
            {'target': 'n', 'display': '佋'},
            {'target': 'n', 'display': '佌'},
            {'target': 'n', 'display': '位'},
            {'target': 'n', 'display': '低'},
            {'target': 'n', 'display': '住'},
            {'target': 'n', 'display': '佐'},
            {'target': 'n', 'display': '佑'},
            {'target': 'n', 'display': '佒'},
            {'target': 'n', 'display': '体'},
            {'target': 'n', 'display': '佔'},
            {'target': 'n', 'display': '何'},
            {'target': 'n', 'display': '佖'},
            {'target': 'b', 'display': '你'},
            {'target': 'b', 'display': '佡'},
            {'target': 'b', 'display': '佢'},
            {'target': 'b', 'display': '佣'},
            {'target': 'b', 'display': '佤'},
            {'target': 'b', 'display': '佥'},
            {'target': 'b', 'display': '佦'},
            {'target': 'b', 'display': '佧'},
            {'target': 'b', 'display': '佨'},
            {'target': 'b', 'display': '佩'},
            {'target': 'b', 'display': '佪'},
            {'target': 'b', 'display': '佫'},
            {'target': 'b', 'display': '佬'},
            {'target': 'b', 'display': '佭'},
            {'target': 'v', 'display': '佰'},
            {'target': 'v', 'display': '佱'},
            {'target': 'v', 'display': '佲'},
            {'target': 'v', 'display': '佳'},
            {'target': 'v', 'display': '佴'},
            {'target': 'v', 'display': '併'},
            {'target': 'v', 'display': '佶'},
            {'target': 'v', 'display': '佷'},
            {'target': 'c', 'display': '侀'},
            {'target': 'c', 'display': '侁'},
            {'target': 'c', 'display': '侂'},
            {'target': 'c', 'display': '侃'},
            {'target': 'c', 'display': '侄'},
            {'target': 'c', 'display': '侅'},
            {'target': 'x', 'display': '侐'},
            {'target': 'x', 'display': '侑'},
            {'target': 'x', 'display': '侒'},
            {'target': 'x', 'display': '侓'},
            {'target': 'x', 'display': '侔'},
            {'target': 'x', 'display': '侕'},
            {'target': 'x', 'display': '侖'},
            {'target': 'x', 'display': '侗'},
        ]
    },
    {
        "name": "第二关：一级简码",
        "maxTime": 120,
        "condition": 1.1,
        "data": [
            {"display": "一"},
            {"display": "地"},
            {"display": "在"},
            {"display": "要"},
            {"display": "工"},
            {"display": "上"},
            {"display": "是"},
            {"display": "中"},
            {"display": "国"},
            {"display": "同"},
            {"display": "和"},
            {"display": "的"},
            {"display": "有"},
            {"display": "人"},
            {"display": "我"},
            {"display": "主"},
            {"display": "产"},
            {"display": "不"},
            {"display": "为"},
            {"display": "这"},
            {"display": "民"},
            {"display": "了"},
            {"display": "发"},
            {"display": "以"},
            {"display": "经"}
        ]
    },
    {
        "name": "第三关：键名汉字",
        "maxTime": 120,
        "condition": 1.5,
        "data": [
            {"display": "金"},
            {"display": "人"},
            {"display": "月"},
            {"display": "白"},
            {"display": "禾"},
            {"display": "言"},
            {"display": "立"},
            {"display": "水"},
            {"display": "火"},
            {"display": "之"},
            {"display": "工"},
            {"display": "木"},
            {"display": "大"},
            {"display": "土"},
            {"display": "王"},
            {"display": "目"},
            {"display": "日"},
            {"display": "口"},
            {"display": "田"},
            {"display": "山"},
            {"display": "已"},
            {"display": "子"},
            {"display": "女"},
            {"display": "又"},
            {"display": "纟"}
        ]
    },
    {
        "name": "第四关：二级简码",
        "maxTime": 120,
        "condition": 1.5,
        "data": [
            {"display": "五"},
            {"display": "于"},
            {"display": "天"},
            {"display": "末"},
            {"display": "开"},
            {"display": "下"},
            {"display": "理"},
            {"display": "事"},
            {"display": "画"},
            {"display": "现"},
            {"display": "玫"},
            {"display": "珠"},
            {"display": "表"},
            {"display": "珍"},
            {"display": "列"},
            {"display": "玉"},
            {"display": "平"},
            {"display": "不"},
            {"display": "来"},
            {"display": "与"},
            {"display": "屯"},
            {"display": "妻"},
            {"display": "到"},
            {"display": "互"},
            {"display": "二"},
            {"display": "寺"},
            {"display": "城"},
            {"display": "霜"},
            {"display": "载"},
            {"display": "直"},
            {"display": "是"},
            {"display": "吉"},
            {"display": "协"},
            {"display": "南"},
            {"display": "才"},
            {"display": "垢"},
            {"display": "圾"},
            {"display": "夫"},
            {"display": "无"},
            {"display": "坟"},
            {"display": "增"},
            {"display": "示"},
            {"display": "赫"},
            {"display": "过"},
            {"display": "志"},
            {"display": "地"},
            {"display": "雪"},
            {"display": "支"},
            {"display": "三"},
            {"display": "夺"},
            {"display": "大"},
            {"display": "厅"},
            {"display": "左"},
            {"display": "丰"},
            {"display": "百"},
            {"display": "右"},
            {"display": "历"},
            {"display": "成"},
            {"display": "帮"},
            {"display": "原"},
            {"display": "胡"},
            {"display": "春"},
            {"display": "克"},
            {"display": "太"},
            {"display": "磁"},
            {"display": "砂"},
            {"display": "灰"},
            {"display": "达"},
            {"display": "成"},
            {"display": "顾"},
            {"display": "肆"},
            {"display": "友"},
            {"display": "龙"},
            {"display": "本"},
            {"display": "村"},
            {"display": "枯"},
            {"display": "林"},
            {"display": "械"},
            {"display": "相"},
            {"display": "查"},
            {"display": "可"},
            {"display": "楞"},
            {"display": "机"},
            {"display": "格"},
            {"display": "析"},
            {"display": "极"},
            {"display": "检"},
            {"display": "构"},
            {"display": "术"},
            {"display": "样"},
            {"display": "档"},
            {"display": "杰"},
            {"display": "棕"},
            {"display": "杨"},
            {"display": "李"},
            {"display": "要"},
            {"display": "权"},
            {"display": "楷"},
            {"display": "七"},
            {"display": "革"},
            {"display": "基"},
            {"display": "苛"},
            {"display": "式"},
            {"display": "牙"},
            {"display": "划"},
            {"display": "或"},
            {"display": "功"},
            {"display": "贡"},
            {"display": "攻"},
            {"display": "匠"},
            {"display": "菜"},
            {"display": "共"},
            {"display": "区"},
            {"display": "芳"},
            {"display": "燕"},
            {"display": "东"},
            {"display": "芝"},
            {"display": "世"},
            {"display": "节"},
            {"display": "切"},
            {"display": "芭"},
            {"display": "药"},
            {"display": "睛"},
            {"display": "睦"},
            {"display": "盯"},
            {"display": "虎"},
            {"display": "止"},
            {"display": "旧"},
            {"display": "占"},
            {"display": "卤"},
            {"display": "贞"},
            {"display": "睡"},
            {"display": "肯"},
            {"display": "具"},
            {"display": "餐"},
            {"display": "眩"},
            {"display": "瞳"},
            {"display": "步"},
            {"display": "眯"},
            {"display": "瞎"},
            {"display": "卢"},
            {"display": "眼"},
            {"display": "皮"},
            {"display": "此"},
            {"display": "量"},
            {"display": "时"},
            {"display": "晨"},
            {"display": "果"},
            {"display": "虹"},
            {"display": "早"},
            {"display": "昌"},
            {"display": "蝇"},
            {"display": "曙"},
            {"display": "遇"},
            {"display": "昨"},
            {"display": "蝗"},
            {"display": "明"},
            {"display": "蛤"},
            {"display": "晚"},
            {"display": "景"},
            {"display": "暗"},
            {"display": "晃"},
            {"display": "显"},
            {"display": "晕"},
            {"display": "电"},
            {"display": "最"},
            {"display": "归"},
            {"display": "紧"},
            {"display": "昆"},
            {"display": "呈"},
            {"display": "叶"},
            {"display": "顺"},
            {"display": "呆"},
            {"display": "呀"},
            {"display": "中"},
            {"display": "虽"},
            {"display": "吕"},
            {"display": "另"},
            {"display": "员"},
            {"display": "呼"},
            {"display": "听"},
            {"display": "吸"},
            {"display": "只"},
            {"display": "史"},
            {"display": "嘛"},
            {"display": "啼"},
            {"display": "吵"},
            {"display": "喧"},
            {"display": "叫"},
            {"display": "啊"},
            {"display": "哪"},
            {"display": "吧"},
            {"display": "哟"},
            {"display": "车"},
            {"display": "轩"},
            {"display": "因"},
            {"display": "困"},
            {"display": "四"},
            {"display": "辊"},
            {"display": "加"},
            {"display": "男"},
            {"display": "轴"},
            {"display": "力"},
            {"display": "斩"},
            {"display": "胃"},
            {"display": "办"},
            {"display": "罗"},
            {"display": "罚"},
            {"display": "较"},
            {"display": "边"},
            {"display": "思"},
            {"display": "轨"},
            {"display": "轻"},
            {"display": "累"},
            {"display": "同"},
            {"display": "财"},
            {"display": "央"},
            {"display": "朵"},
            {"display": "曲"},
            {"display": "由"},
            {"display": "则"},
            {"display": "崭"},
            {"display": "册"},
            {"display": "几"},
            {"display": "贩"},
            {"display": "骨"},
            {"display": "内"},
            {"display": "风"},
            {"display": "凡"},
            {"display": "赠"},
            {"display": "峭"},
            {"display": "迪"},
            {"display": "岂"},
            {"display": "邮"},
            {"display": "凤"},
            {"display": "生"},
            {"display": "行"},
            {"display": "知"},
            {"display": "条"},
            {"display": "长"},
            {"display": "处"},
            {"display": "得"},
            {"display": "各"},
            {"display": "力"},
            {"display": "向"},
            {"display": "笔"},
            {"display": "物"},
            {"display": "秀"},
            {"display": "答"},
            {"display": "称"},
            {"display": "入"},
            {"display": "科"},
            {"display": "秒"},
            {"display": "管"},
            {"display": "秘"},
            {"display": "季"},
            {"display": "委"},
            {"display": "么"},
            {"display": "第"},
            {"display": "后"},
            {"display": "持"},
            {"display": "拓"},
            {"display": "打"},
            {"display": "找"},
            {"display": "年"},
            {"display": "提"},
            {"display": "扣"},
            {"display": "押"},
            {"display": "抽"},
            {"display": "手"},
            {"display": "折"},
            {"display": "扔"},
            {"display": "失"},
            {"display": "换"},
            {"display": "扩"},
            {"display": "拉"},
            {"display": "朱"},
            {"display": "搂"},
            {"display": "近"},
            {"display": "所"},
            {"display": "报"},
            {"display": "扫"},
            {"display": "反"},
            {"display": "批"},
            {"display": "且"},
            {"display": "肝"},
            {"display": "肛"},
            {"display": "胆"},
            {"display": "肿"},
            {"display": "肋"},
            {"display": "肌"},
            {"display": "用"},
            {"display": "遥"},
            {"display": "朋"},
            {"display": "脸"},
            {"display": "胸"},
            {"display": "及"},
            {"display": "胶"},
            {"display": "膛"},
            {"display": "爱"},
            {"display": "甩"},
            {"display": "服"},
            {"display": "妥"},
            {"display": "肥"},
            {"display": "脂"},
            {"display": "全"},
            {"display": "会"},
            {"display": "估"},
            {"display": "休"},
            {"display": "代"},
            {"display": "个"},
            {"display": "介"},
            {"display": "保"},
            {"display": "佃"},
            {"display": "仙"},
            {"display": "作"},
            {"display": "伯"},
            {"display": "仍"},
            {"display": "从"},
            {"display": "你"},
            {"display": "信"},
            {"display": "们"},
            {"display": "偿"},
            {"display": "伙"},
            {"display": "亿"},
            {"display": "他"},
            {"display": "分"},
            {"display": "公"},
            {"display": "化"},
            {"display": "钱"},
            {"display": "针"},
            {"display": "然"},
            {"display": "钉"},
            {"display": "氏"},
            {"display": "外"},
            {"display": "旬"},
            {"display": "名"},
            {"display": "锣"},
            {"display": "负"},
            {"display": "儿"},
            {"display": "铁"},
            {"display": "角"},
            {"display": "欠"},
            {"display": "多"},
            {"display": "久"},
            {"display": "匀"},
            {"display": "乐"},
            {"display": "炙"},
            {"display": "锭"},
            {"display": "包"},
            {"display": "凶"},
            {"display": "争"},
            {"display": "色"},
            {"display": "主"},
            {"display": "计"},
            {"display": "庆"},
            {"display": "订"},
            {"display": "度"},
            {"display": "让"},
            {"display": "刘"},
            {"display": "训"},
            {"display": "为"},
            {"display": "高"},
            {"display": "放"},
            {"display": "诉"},
            {"display": "衣"},
            {"display": "认"},
            {"display": "义"},
            {"display": "方"},
            {"display": "说"},
            {"display": "就"},
            {"display": "变"},
            {"display": "这"},
            {"display": "记"},
            {"display": "离"},
            {"display": "良"},
            {"display": "充"},
            {"display": "率"},
            {"display": "闰"},
            {"display": "半"},
            {"display": "关"},
            {"display": "亲"},
            {"display": "并"},
            {"display": "站"},
            {"display": "间"},
            {"display": "部"},
            {"display": "曾"},
            {"display": "商"},
            {"display": "产"},
            {"display": "瓣"},
            {"display": "前"},
            {"display": "闪"},
            {"display": "交"},
            {"display": "六"},
            {"display": "立"},
            {"display": "冰"},
            {"display": "普"},
            {"display": "帝"},
            {"display": "决"},
            {"display": "闻"},
            {"display": "妆"},
            {"display": "冯"},
            {"display": "北"},
            {"display": "汪"},
            {"display": "法"},
            {"display": "尖"},
            {"display": "洒"},
            {"display": "江"},
            {"display": "小"},
            {"display": "浊"},
            {"display": "澡"},
            {"display": "渐"},
            {"display": "没"},
            {"display": "少"},
            {"display": "泊"},
            {"display": "肖"},
            {"display": "兴"},
            {"display": "光"},
            {"display": "注"},
            {"display": "洋"},
            {"display": "水"},
            {"display": "淡"},
            {"display": "学"},
            {"display": "沁"},
            {"display": "池"},
            {"display": "当"},
            {"display": "汉"},
            {"display": "涨"},
            {"display": "业"},
            {"display": "灶"},
            {"display": "类"},
            {"display": "灯"},
            {"display": "煤"},
            {"display": "粘"},
            {"display": "烛"},
            {"display": "炽"},
            {"display": "烟"},
            {"display": "灿"},
            {"display": "烽"},
            {"display": "煌"},
            {"display": "粗"},
            {"display": "伙"},
            {"display": "炮"},
            {"display": "米"},
            {"display": "料"},
            {"display": "炒"},
            {"display": "炎"},
            {"display": "迷"},
            {"display": "断"},
            {"display": "籽"},
            {"display": "娄"},
            {"display": "烃"},
            {"display": "定"},
            {"display": "守"},
            {"display": "害"},
            {"display": "宁"},
            {"display": "宽"},
            {"display": "寂"},
            {"display": "审"},
            {"display": "宫"},
            {"display": "军"},
            {"display": "宙"},
            {"display": "客"},
            {"display": "宾"},
            {"display": "家"},
            {"display": "空"},
            {"display": "宛"},
            {"display": "社"},
            {"display": "实"},
            {"display": "宵"},
            {"display": "灾"},
            {"display": "之"},
            {"display": "官"},
            {"display": "字"},
            {"display": "安"},
            {"display": "它"},
            {"display": "怀"},
            {"display": "导"},
            {"display": "居"},
            {"display": "民"},
            {"display": "收"},
            {"display": "慢"},
            {"display": "避"},
            {"display": "惭"},
            {"display": "届"},
            {"display": "必"},
            {"display": "怕"},
            {"display": "愉"},
            {"display": "懈"},
            {"display": "心"},
            {"display": "习"},
            {"display": "悄"},
            {"display": "屡"},
            {"display": "忱"},
            {"display": "忆"},
            {"display": "敢"},
            {"display": "恨"},
            {"display": "怪"},
            {"display": "尼"},
            {"display": "卫"},
            {"display": "际"},
            {"display": "承"},
            {"display": "阿"},
            {"display": "陈"},
            {"display": "耻"},
            {"display": "阳"},
            {"display": "职"},
            {"display": "阵"},
            {"display": "出"},
            {"display": "降"},
            {"display": "孤"},
            {"display": "阴"},
            {"display": "队"},
            {"display": "隐"},
            {"display": "防"},
            {"display": "联"},
            {"display": "孙"},
            {"display": "耿"},
            {"display": "辽"},
            {"display": "也"},
            {"display": "子"},
            {"display": "限"},
            {"display": "取"},
            {"display": "陛"},
            {"display": "姨"},
            {"display": "寻"},
            {"display": "姑"},
            {"display": "杂"},
            {"display": "毁"},
            {"display": "旭"},
            {"display": "如"},
            {"display": "舅"},
            {"display": "九"},
            {"display": "奶"},
            {"display": "婚"},
            {"display": "妨"},
            {"display": "嫌"},
            {"display": "录"},
            {"display": "灵"},
            {"display": "巡"},
            {"display": "刀"},
            {"display": "好"},
            {"display": "妇"},
            {"display": "妈"},
            {"display": "姆"},
            {"display": "对"},
            {"display": "参"},
            {"display": "戏"},
            {"display": "台"},
            {"display": "劝"},
            {"display": "观"},
            {"display": "矣"},
            {"display": "牟"},
            {"display": "能"},
            {"display": "难"},
            {"display": "允"},
            {"display": "驻"},
            {"display": "驼"},
            {"display": "马"},
            {"display": "邓"},
            {"display": "艰"},
            {"display": "线"},
            {"display": "结"},
            {"display": "顷"},
            {"display": "红"},
            {"display": "引"},
            {"display": "旨"},
            {"display": "强"},
            {"display": "细"},
            {"display": "纲"},
            {"display": "张"},
            {"display": "绵"},
            {"display": "级"},
            {"display": "给"},
            {"display": "约"},
            {"display": "纺"},
            {"display": "弱"},
            {"display": "纱"},
            {"display": "继"},
            {"display": "综"},
            {"display": "纪"},
            {"display": "弛"},
            {"display": "绿"},
            {"display": "经"},
            {"display": "比"},
            {"display": "五"},
            {"display": "于"},
            {"display": "天"},
            {"display": "末"},
            {"display": "开"},
            {"display": "下"},
            {"display": "理"},
            {"display": "事"},
            {"display": "画"},
            {"display": "现"},
            {"display": "玫"},
            {"display": "珠"},
            {"display": "表"},
            {"display": "珍"},
            {"display": "列"},
            {"display": "玉"},
            {"display": "平"},
            {"display": "不"},
            {"display": "来"},
            {"display": "与"},
            {"display": "屯"},
            {"display": "妻"},
            {"display": "到"},
            {"display": "互"},
            {"display": "二"},
            {"display": "寺"},
            {"display": "城"},
            {"display": "霜"},
            {"display": "载"},
            {"display": "直"},
            {"display": "是"},
            {"display": "吉"},
            {"display": "协"},
            {"display": "南"},
            {"display": "才"},
            {"display": "垢"},
            {"display": "圾"},
            {"display": "夫"},
            {"display": "无"},
            {"display": "坟"},
            {"display": "增"},
            {"display": "示"},
            {"display": "赫"},
            {"display": "过"},
            {"display": "志"},
            {"display": "地"},
            {"display": "雪"},
            {"display": "支"},
            {"display": "三"},
            {"display": "夺"},
            {"display": "大"},
            {"display": "厅"},
            {"display": "左"},
            {"display": "丰"},
            {"display": "百"},
            {"display": "右"},
            {"display": "历"},
            {"display": "成"},
            {"display": "帮"},
            {"display": "原"},
            {"display": "胡"},
            {"display": "春"},
            {"display": "克"},
            {"display": "太"},
            {"display": "磁"},
            {"display": "砂"},
            {"display": "灰"},
            {"display": "达"},
            {"display": "成"},
            {"display": "顾"},
            {"display": "肆"},
            {"display": "友"},
            {"display": "龙"},
            {"display": "本"},
            {"display": "村"},
            {"display": "枯"},
            {"display": "林"},
            {"display": "械"},
            {"display": "相"},
            {"display": "查"},
            {"display": "可"},
            {"display": "楞"},
            {"display": "机"},
            {"display": "格"},
            {"display": "析"},
            {"display": "极"},
            {"display": "检"},
            {"display": "构"},
            {"display": "术"},
            {"display": "样"},
            {"display": "档"},
            {"display": "杰"},
            {"display": "棕"},
            {"display": "杨"},
            {"display": "李"},
            {"display": "要"},
            {"display": "权"},
            {"display": "楷"},
            {"display": "七"},
            {"display": "革"},
            {"display": "基"},
            {"display": "苛"},
            {"display": "式"},
            {"display": "牙"},
            {"display": "划"},
            {"display": "或"},
            {"display": "功"},
            {"display": "贡"},
            {"display": "攻"},
            {"display": "匠"},
            {"display": "菜"},
            {"display": "共"},
            {"display": "区"},
            {"display": "芳"},
            {"display": "燕"},
            {"display": "东"},
            {"display": "芝"},
            {"display": "世"},
            {"display": "节"},
            {"display": "切"},
            {"display": "芭"},
            {"display": "药"},
            {"display": "睛"},
            {"display": "睦"},
            {"display": "盯"},
            {"display": "虎"},
            {"display": "止"},
            {"display": "旧"},
            {"display": "占"},
            {"display": "卤"},
            {"display": "贞"},
            {"display": "睡"},
            {"display": "肯"},
            {"display": "具"},
            {"display": "餐"},
            {"display": "眩"},
            {"display": "瞳"},
            {"display": "步"},
            {"display": "眯"},
            {"display": "瞎"},
            {"display": "卢"},
            {"display": "眼"},
            {"display": "皮"},
            {"display": "此"},
            {"display": "量"},
            {"display": "时"},
            {"display": "晨"},
            {"display": "果"},
            {"display": "虹"},
            {"display": "早"},
            {"display": "昌"},
            {"display": "蝇"},
            {"display": "曙"},
            {"display": "遇"},
            {"display": "昨"},
            {"display": "蝗"},
            {"display": "明"},
            {"display": "蛤"},
            {"display": "晚"},
            {"display": "景"},
            {"display": "暗"},
            {"display": "晃"},
            {"display": "显"},
            {"display": "晕"},
            {"display": "电"},
            {"display": "最"},
            {"display": "归"},
            {"display": "紧"},
            {"display": "昆"},
            {"display": "呈"},
            {"display": "叶"},
            {"display": "顺"},
            {"display": "呆"},
            {"display": "呀"},
            {"display": "中"},
            {"display": "虽"},
            {"display": "吕"},
            {"display": "另"},
            {"display": "员"},
            {"display": "呼"},
            {"display": "听"},
            {"display": "吸"},
            {"display": "只"},
            {"display": "史"},
            {"display": "嘛"},
            {"display": "啼"},
            {"display": "吵"},
            {"display": "喧"},
            {"display": "叫"},
            {"display": "啊"},
            {"display": "哪"},
            {"display": "吧"},
            {"display": "哟"},
            {"display": "车"},
            {"display": "轩"},
            {"display": "因"},
            {"display": "困"},
            {"display": "四"},
            {"display": "辊"},
            {"display": "加"},
            {"display": "男"},
            {"display": "轴"},
            {"display": "力"},
            {"display": "斩"},
            {"display": "胃"},
            {"display": "办"},
            {"display": "罗"},
            {"display": "罚"},
            {"display": "较"},
            {"display": "边"},
            {"display": "思"},
            {"display": "轨"},
            {"display": "轻"},
            {"display": "累"},
            {"display": "同"},
            {"display": "财"},
            {"display": "央"},
            {"display": "朵"},
            {"display": "曲"},
            {"display": "由"},
            {"display": "则"},
            {"display": "崭"},
            {"display": "册"},
            {"display": "几"},
            {"display": "贩"},
            {"display": "骨"},
            {"display": "内"},
            {"display": "风"},
            {"display": "凡"},
            {"display": "赠"},
            {"display": "峭"},
            {"display": "迪"},
            {"display": "岂"},
            {"display": "邮"},
            {"display": "凤"}
        ]
    },
]
