levels = [
    {
        "name": "第零关：指法练习",
        "maxTime": 1024,
        "condition": 0.8,
        "data": [
            {"display": "a"},
            {"display": "b"},
            {"display": "c"},
            {"display": "d"},
            {"display": "e"},
            {"display": "f"},
            {"display": "g"},
            {"display": "h"},
            {"display": "i"},
            {"display": "j"},
            {"display": "k"},
            {"display": "l"},
            {"display": "m"},
            {"display": "n"},
            {"display": "o"},
            {"display": "p"},
            {"display": "q"},
            {"display": "r"},
            {"display": "s"},
            {"display": "t"},
            {"display": "u"},
            {"display": "v"},
            {"display": "w"},
            {"display": "x"},
            {"display": "y"},
            {"display": "z"}
        ]
    },
    {
        "name": "第二关：字根输入",
        "maxTime": 10240,
        "condition": 0.9,
        "data": [
            {'target': 'g', 'display': '一'},
            {'target': 'g', 'display': '丁'},
            {'target': 'g', 'display': '丂'},
            {'target': 'g', 'display': '七'},
            {'target': 'g', 'display': '丄'},
            {'target': 'g', 'display': '丅'},
            {'target': 'f', 'display': '丐'},
            {'target': 'f', 'display': '丑'},
            {'target': 'f', 'display': '丒'},
            {'target': 'f', 'display': '专'},
            {'target': 'f', 'display': '且'},
            {'target': 'f', 'display': '丕'},
            {'target': 'f', 'display': '世'},
            {'target': 'f', 'display': '丗'},
            {'target': 'f', 'display': '丘'},
            {'target': 'f', 'display': '丙'},
            {'target': 'd', 'display': '丠'},
            {'target': 'd', 'display': '両'},
            {'target': 'd', 'display': '丢'},
            {'target': 'd', 'display': '丣'},
            {'target': 'd', 'display': '两'},
            {'target': 'd', 'display': '严'},
            {'target': 'd', 'display': '並'},
            {'target': 'd', 'display': '丧'},
            {'target': 'd', 'display': '丨'},
            {'target': 'd', 'display': '丩'},
            {'target': 'd', 'display': '个'},
            {'target': 'd', 'display': '丫'},
            {'target': 's', 'display': '丰'},
            {'target': 's', 'display': '丱'},
            {'target': 's', 'display': '串'},
            {'target': 's', 'display': '丳'},
            {'target': 'a', 'display': '乀'},
            {'target': 'a', 'display': '乁'},
            {'target': 'a', 'display': '乂'},
            {'target': 'a', 'display': '乃'},
            {'target': 'a', 'display': '乄'},
            {'target': 'a', 'display': '久'},
            {'target': 'a', 'display': '乆'},
            {'target': 'a', 'display': '乇'},
            {'target': 'a', 'display': '么'},
            {'target': 'a', 'display': '义'},
            {'target': 'a', 'display': '乊'},
            {'target': 'a', 'display': '之'},
            {'target': 'a', 'display': '乌'},
            {'target': 'a', 'display': '乍'},
            {'target': 'h', 'display': '乐'},
            {'target': 'h', 'display': '乑'},
            {'target': 'h', 'display': '乒'},
            {'target': 'h', 'display': '乓'},
            {'target': 'h', 'display': '乔'},
            {'target': 'h', 'display': '乕'},
            {'target': 'h', 'display': '乖'},
            {'target': 'h', 'display': '乗'},
            {'target': 'h', 'display': '乘'},
            {'target': 'h', 'display': '乙'},
            {'target': 'h', 'display': '乚'},
            {'target': 'j', 'display': '习'},
            {'target': 'j', 'display': '乡'},
            {'target': 'j', 'display': '乢'},
            {'target': 'j', 'display': '乣'},
            {'target': 'j', 'display': '乤'},
            {'target': 'j', 'display': '乥'},
            {'target': 'j', 'display': '书'},
            {'target': 'j', 'display': '乧'},
            {'target': 'j', 'display': '乨'},
            {'target': 'k', 'display': '买'},
            {'target': 'k', 'display': '乱'},
            {'target': 'k', 'display': '乲'},
            {'target': 'l', 'display': '亀'},
            {'target': 'l', 'display': '亁'},
            {'target': 'l', 'display': '亂'},
            {'target': 'l', 'display': '亃'},
            {'target': 'l', 'display': '亄'},
            {'target': 'l', 'display': '亅'},
            {'target': 'l', 'display': '了'},
            {'target': 'l', 'display': '亇'},
            {'target': 'l', 'display': '予'},
            {'target': 'l', 'display': '争'},
            {'target': 'l', 'display': '亊'},
            {'target': 'm', 'display': '亐'},
            {'target': 'm', 'display': '云'},
            {'target': 'm', 'display': '互'},
            {'target': 'm', 'display': '亓'},
            {'target': 'm', 'display': '五'},
            {'target': 'm', 'display': '井'},
            {'target': 'm', 'display': '亖'},
            {'target': 'm', 'display': '亗'},
            {'target': 't', 'display': '亠'},
            {'target': 't', 'display': '亡'},
            {'target': 't', 'display': '亢'},
            {'target': 't', 'display': '亣'},
            {'target': 't', 'display': '交'},
            {'target': 't', 'display': '亥'},
            {'target': 't', 'display': '亦'},
            {'target': 't', 'display': '产'},
            {'target': 't', 'display': '亨'},
            {'target': 'r', 'display': '亰'},
            {'target': 'r', 'display': '亱'},
            {'target': 'r', 'display': '亲'},
            {'target': 'r', 'display': '亳'},
            {'target': 'r', 'display': '亴'},
            {'target': 'r', 'display': '亵'},
            {'target': 'r', 'display': '亶'},
            {'target': 'r', 'display': '亷'},
            {'target': 'r', 'display': '亸'},
            {'target': 'r', 'display': '亹'},
            {'target': 'e', 'display': '什'},
            {'target': 'e', 'display': '仁'},
            {'target': 'e', 'display': '仂'},
            {'target': 'e', 'display': '仃'},
            {'target': 'e', 'display': '仄'},
            {'target': 'e', 'display': '仅'},
            {'target': 'e', 'display': '仆'},
            {'target': 'e', 'display': '仇'},
            {'target': 'e', 'display': '仈'},
            {'target': 'e', 'display': '仉'},
            {'target': 'e', 'display': '今'},
            {'target': 'e', 'display': '介'},
            {'target': 'e', 'display': '仌'},
            {'target': 'w', 'display': '仐'},
            {'target': 'w', 'display': '仑'},
            {'target': 'w', 'display': '仒'},
            {'target': 'w', 'display': '仓'},
            {'target': 'w', 'display': '仔'},
            {'target': 'q', 'display': '仠'},
            {'target': 'q', 'display': '仡'},
            {'target': 'q', 'display': '仢'},
            {'target': 'q', 'display': '代'},
            {'target': 'q', 'display': '令'},
            {'target': 'q', 'display': '以'},
            {'target': 'q', 'display': '仦'},
            {'target': 'q', 'display': '仧'},
            {'target': 'q', 'display': '仨'},
            {'target': 'q', 'display': '仩'},
            {'target': 'q', 'display': '仪'},
            {'target': 'q', 'display': '仫'},
            {'target': 'q', 'display': '们'},
            {'target': 'q', 'display': '仭'},
            {'target': 'q', 'display': '仮'},
            {'target': 'y', 'display': '仰'},
            {'target': 'y', 'display': '仱'},
            {'target': 'y', 'display': '仲'},
            {'target': 'y', 'display': '仳'},
            {'target': 'y', 'display': '仴'},
            {'target': 'y', 'display': '仵'},
            {'target': 'y', 'display': '件'},
            {'target': 'y', 'display': '价'},
            {'target': 'y', 'display': '仸'},
            {'target': 'y', 'display': '仹'},
            {'target': 'u', 'display': '伀'},
            {'target': 'u', 'display': '企'},
            {'target': 'u', 'display': '伂'},
            {'target': 'u', 'display': '伃'},
            {'target': 'u', 'display': '伄'},
            {'target': 'u', 'display': '伅'},
            {'target': 'u', 'display': '伆'},
            {'target': 'u', 'display': '伇'},
            {'target': 'u', 'display': '伈'},
            {'target': 'u', 'display': '伉'},
            {'target': 'u', 'display': '伊'},
            {'target': 'u', 'display': '伋'},
            {'target': 'u', 'display': '伌'},
            {'target': 'i', 'display': '伐'},
            {'target': 'i', 'display': '休'},
            {'target': 'i', 'display': '伒'},
            {'target': 'i', 'display': '伓'},
            {'target': 'i', 'display': '伔'},
            {'target': 'i', 'display': '伕'},
            {'target': 'i', 'display': '伖'},
            {'target': 'i', 'display': '众'},
            {'target': 'i', 'display': '优'},
            {'target': 'i', 'display': '伙'},
            {'target': 'i', 'display': '会'},
            {'target': 'p', 'display': '估'},
            {'target': 'p', 'display': '伱'},
            {'target': 'p', 'display': '伲'},
            {'target': 'p', 'display': '伳'},
            {'target': 'p', 'display': '伴'},
            {'target': 'p', 'display': '伵'},
            {'target': 'n', 'display': '佀'},
            {'target': 'n', 'display': '佁'},
            {'target': 'n', 'display': '佂'},
            {'target': 'n', 'display': '佃'},
            {'target': 'n', 'display': '佄'},
            {'target': 'n', 'display': '佅'},
            {'target': 'n', 'display': '但'},
            {'target': 'n', 'display': '佇'},
            {'target': 'n', 'display': '佈'},
            {'target': 'n', 'display': '佉'},
            {'target': 'n', 'display': '佊'},
            {'target': 'n', 'display': '佋'},
            {'target': 'n', 'display': '佌'},
            {'target': 'n', 'display': '位'},
            {'target': 'n', 'display': '低'},
            {'target': 'n', 'display': '住'},
            {'target': 'n', 'display': '佐'},
            {'target': 'n', 'display': '佑'},
            {'target': 'n', 'display': '佒'},
            {'target': 'n', 'display': '体'},
            {'target': 'n', 'display': '佔'},
            {'target': 'n', 'display': '何'},
            {'target': 'n', 'display': '佖'},
            {'target': 'b', 'display': '你'},
            {'target': 'b', 'display': '佡'},
            {'target': 'b', 'display': '佢'},
            {'target': 'b', 'display': '佣'},
            {'target': 'b', 'display': '佤'},
            {'target': 'b', 'display': '佥'},
            {'target': 'b', 'display': '佦'},
            {'target': 'b', 'display': '佧'},
            {'target': 'b', 'display': '佨'},
            {'target': 'b', 'display': '佩'},
            {'target': 'b', 'display': '佪'},
            {'target': 'b', 'display': '佫'},
            {'target': 'b', 'display': '佬'},
            {'target': 'b', 'display': '佭'},
            {'target': 'v', 'display': '佰'},
            {'target': 'v', 'display': '佱'},
            {'target': 'v', 'display': '佲'},
            {'target': 'v', 'display': '佳'},
            {'target': 'v', 'display': '佴'},
            {'target': 'v', 'display': '併'},
            {'target': 'v', 'display': '佶'},
            {'target': 'v', 'display': '佷'},
            {'target': 'c', 'display': '侀'},
            {'target': 'c', 'display': '侁'},
            {'target': 'c', 'display': '侂'},
            {'target': 'c', 'display': '侃'},
            {'target': 'c', 'display': '侄'},
            {'target': 'c', 'display': '侅'},
            {'target': 'x', 'display': '侐'},
            {'target': 'x', 'display': '侑'},
            {'target': 'x', 'display': '侒'},
            {'target': 'x', 'display': '侓'},
            {'target': 'x', 'display': '侔'},
            {'target': 'x', 'display': '侕'},
            {'target': 'x', 'display': '侖'},
            {'target': 'x', 'display': '侗'},
        ]
    }
]
