levels = [
    {
        "name": "指法练习",
        "maxTime": 120,
        "condition": 1.0,
        "data": [
            {"display": "a"},
            {"display": "b"},
            {"display": "c"},
            {"display": "d"},
            {"display": "e"},
            {"display": "f"},
            {"display": "g"},
            {"display": "h"},
            {"display": "i"},
            {"display": "j"},
            {"display": "k"},
            {"display": "l"},
            {"display": "m"},
            {"display": "n"},
            {"display": "o"},
            {"display": "p"},
            {"display": "q"},
            {"display": "r"},
            {"display": "s"},
            {"display": "t"},
            {"display": "u"},
            {"display": "v"},
            {"display": "w"},
            {"display": "x"},
            {"display": "y"},
            {"display": "z"}
        ]
    },
    {
        "name": "字根输入",
        "maxTime": 120,
        "condition": 1.2,
        "data": [
            {'target': 'g', 'display': '一'},
            {'target': 'g', 'display': '丁'},
            {'target': 'g', 'display': '丂'},
            {'target': 'g', 'display': '七'},
            {'target': 'g', 'display': '丄'},
            {'target': 'g', 'display': '丅'},
            {'target': 'f', 'display': '丐'},
            {'target': 'f', 'display': '丑'},
            {'target': 'f', 'display': '丒'},
            {'target': 'f', 'display': '专'},
            {'target': 'f', 'display': '且'},
            {'target': 'f', 'display': '丕'},
            {'target': 'f', 'display': '世'},
            {'target': 'f', 'display': '丗'},
            {'target': 'f', 'display': '丘'},
            {'target': 'f', 'display': '丙'},
            {'target': 'd', 'display': '丠'},
            {'target': 'd', 'display': '両'},
            {'target': 'd', 'display': '丢'},
            {'target': 'd', 'display': '丣'},
            {'target': 'd', 'display': '两'},
            {'target': 'd', 'display': '严'},
            {'target': 'd', 'display': '並'},
            {'target': 'd', 'display': '丧'},
            {'target': 'd', 'display': '丨'},
            {'target': 'd', 'display': '丩'},
            {'target': 'd', 'display': '个'},
            {'target': 'd', 'display': '丫'},
            {'target': 's', 'display': '丰'},
            {'target': 's', 'display': '丱'},
            {'target': 's', 'display': '串'},
            {'target': 's', 'display': '丳'},
            {'target': 'a', 'display': '乀'},
            {'target': 'a', 'display': '乁'},
            {'target': 'a', 'display': '乂'},
            {'target': 'a', 'display': '乃'},
            {'target': 'a', 'display': '乄'},
            {'target': 'a', 'display': '久'},
            {'target': 'a', 'display': '乆'},
            {'target': 'a', 'display': '乇'},
            {'target': 'a', 'display': '么'},
            {'target': 'a', 'display': '义'},
            {'target': 'a', 'display': '乊'},
            {'target': 'a', 'display': '之'},
            {'target': 'a', 'display': '乌'},
            {'target': 'a', 'display': '乍'},
            {'target': 'h', 'display': '乐'},
            {'target': 'h', 'display': '乑'},
            {'target': 'h', 'display': '乒'},
            {'target': 'h', 'display': '乓'},
            {'target': 'h', 'display': '乔'},
            {'target': 'h', 'display': '乕'},
            {'target': 'h', 'display': '乖'},
            {'target': 'h', 'display': '乗'},
            {'target': 'h', 'display': '乘'},
            {'target': 'h', 'display': '乙'},
            {'target': 'h', 'display': '乚'},
            {'target': 'j', 'display': '习'},
            {'target': 'j', 'display': '乡'},
            {'target': 'j', 'display': '乢'},
            {'target': 'j', 'display': '乣'},
            {'target': 'j', 'display': '乤'},
            {'target': 'j', 'display': '乥'},
            {'target': 'j', 'display': '书'},
            {'target': 'j', 'display': '乧'},
            {'target': 'j', 'display': '乨'},
            {'target': 'k', 'display': '买'},
            {'target': 'k', 'display': '乱'},
            {'target': 'k', 'display': '乲'},
            {'target': 'l', 'display': '亀'},
            {'target': 'l', 'display': '亁'},
            {'target': 'l', 'display': '亂'},
            {'target': 'l', 'display': '亃'},
            {'target': 'l', 'display': '亄'},
            {'target': 'l', 'display': '亅'},
            {'target': 'l', 'display': '了'},
            {'target': 'l', 'display': '亇'},
            {'target': 'l', 'display': '予'},
            {'target': 'l', 'display': '争'},
            {'target': 'l', 'display': '亊'},
            {'target': 'm', 'display': '亐'},
            {'target': 'm', 'display': '云'},
            {'target': 'm', 'display': '互'},
            {'target': 'm', 'display': '亓'},
            {'target': 'm', 'display': '五'},
            {'target': 'm', 'display': '井'},
            {'target': 'm', 'display': '亖'},
            {'target': 'm', 'display': '亗'},
            {'target': 't', 'display': '亠'},
            {'target': 't', 'display': '亡'},
            {'target': 't', 'display': '亢'},
            {'target': 't', 'display': '亣'},
            {'target': 't', 'display': '交'},
            {'target': 't', 'display': '亥'},
            {'target': 't', 'display': '亦'},
            {'target': 't', 'display': '产'},
            {'target': 't', 'display': '亨'},
            {'target': 'r', 'display': '亰'},
            {'target': 'r', 'display': '亱'},
            {'target': 'r', 'display': '亲'},
            {'target': 'r', 'display': '亳'},
            {'target': 'r', 'display': '亴'},
            {'target': 'r', 'display': '亵'},
            {'target': 'r', 'display': '亶'},
            {'target': 'r', 'display': '亷'},
            {'target': 'r', 'display': '亸'},
            {'target': 'r', 'display': '亹'},
            {'target': 'e', 'display': '什'},
            {'target': 'e', 'display': '仁'},
            {'target': 'e', 'display': '仂'},
            {'target': 'e', 'display': '仃'},
            {'target': 'e', 'display': '仄'},
            {'target': 'e', 'display': '仅'},
            {'target': 'e', 'display': '仆'},
            {'target': 'e', 'display': '仇'},
            {'target': 'e', 'display': '仈'},
            {'target': 'e', 'display': '仉'},
            {'target': 'e', 'display': '今'},
            {'target': 'e', 'display': '介'},
            {'target': 'e', 'display': '仌'},
            {'target': 'w', 'display': '仐'},
            {'target': 'w', 'display': '仑'},
            {'target': 'w', 'display': '仒'},
            {'target': 'w', 'display': '仓'},
            {'target': 'w', 'display': '仔'},
            {'target': 'q', 'display': '仠'},
            {'target': 'q', 'display': '仡'},
            {'target': 'q', 'display': '仢'},
            {'target': 'q', 'display': '代'},
            {'target': 'q', 'display': '令'},
            {'target': 'q', 'display': '以'},
            {'target': 'q', 'display': '仦'},
            {'target': 'q', 'display': '仧'},
            {'target': 'q', 'display': '仨'},
            {'target': 'q', 'display': '仩'},
            {'target': 'q', 'display': '仪'},
            {'target': 'q', 'display': '仫'},
            {'target': 'q', 'display': '们'},
            {'target': 'q', 'display': '仭'},
            {'target': 'q', 'display': '仮'},
            {'target': 'y', 'display': '仰'},
            {'target': 'y', 'display': '仱'},
            {'target': 'y', 'display': '仲'},
            {'target': 'y', 'display': '仳'},
            {'target': 'y', 'display': '仴'},
            {'target': 'y', 'display': '仵'},
            {'target': 'y', 'display': '件'},
            {'target': 'y', 'display': '价'},
            {'target': 'y', 'display': '仸'},
            {'target': 'y', 'display': '仹'},
            {'target': 'u', 'display': '伀'},
            {'target': 'u', 'display': '企'},
            {'target': 'u', 'display': '伂'},
            {'target': 'u', 'display': '伃'},
            {'target': 'u', 'display': '伄'},
            {'target': 'u', 'display': '伅'},
            {'target': 'u', 'display': '伆'},
            {'target': 'u', 'display': '伇'},
            {'target': 'u', 'display': '伈'},
            {'target': 'u', 'display': '伉'},
            {'target': 'u', 'display': '伊'},
            {'target': 'u', 'display': '伋'},
            {'target': 'u', 'display': '伌'},
            {'target': 'i', 'display': '伐'},
            {'target': 'i', 'display': '休'},
            {'target': 'i', 'display': '伒'},
            {'target': 'i', 'display': '伓'},
            {'target': 'i', 'display': '伔'},
            {'target': 'i', 'display': '伕'},
            {'target': 'i', 'display': '伖'},
            {'target': 'i', 'display': '众'},
            {'target': 'i', 'display': '优'},
            {'target': 'i', 'display': '伙'},
            {'target': 'i', 'display': '会'},
            {'target': 'p', 'display': '估'},
            {'target': 'p', 'display': '伱'},
            {'target': 'p', 'display': '伲'},
            {'target': 'p', 'display': '伳'},
            {'target': 'p', 'display': '伴'},
            {'target': 'p', 'display': '伵'},
            {'target': 'n', 'display': '佀'},
            {'target': 'n', 'display': '佁'},
            {'target': 'n', 'display': '佂'},
            {'target': 'n', 'display': '佃'},
            {'target': 'n', 'display': '佄'},
            {'target': 'n', 'display': '佅'},
            {'target': 'n', 'display': '但'},
            {'target': 'n', 'display': '佇'},
            {'target': 'n', 'display': '佈'},
            {'target': 'n', 'display': '佉'},
            {'target': 'n', 'display': '佊'},
            {'target': 'n', 'display': '佋'},
            {'target': 'n', 'display': '佌'},
            {'target': 'n', 'display': '位'},
            {'target': 'n', 'display': '低'},
            {'target': 'n', 'display': '住'},
            {'target': 'n', 'display': '佐'},
            {'target': 'n', 'display': '佑'},
            {'target': 'n', 'display': '佒'},
            {'target': 'n', 'display': '体'},
            {'target': 'n', 'display': '佔'},
            {'target': 'n', 'display': '何'},
            {'target': 'n', 'display': '佖'},
            {'target': 'b', 'display': '你'},
            {'target': 'b', 'display': '佡'},
            {'target': 'b', 'display': '佢'},
            {'target': 'b', 'display': '佣'},
            {'target': 'b', 'display': '佤'},
            {'target': 'b', 'display': '佥'},
            {'target': 'b', 'display': '佦'},
            {'target': 'b', 'display': '佧'},
            {'target': 'b', 'display': '佨'},
            {'target': 'b', 'display': '佩'},
            {'target': 'b', 'display': '佪'},
            {'target': 'b', 'display': '佫'},
            {'target': 'b', 'display': '佬'},
            {'target': 'b', 'display': '佭'},
            {'target': 'v', 'display': '佰'},
            {'target': 'v', 'display': '佱'},
            {'target': 'v', 'display': '佲'},
            {'target': 'v', 'display': '佳'},
            {'target': 'v', 'display': '佴'},
            {'target': 'v', 'display': '併'},
            {'target': 'v', 'display': '佶'},
            {'target': 'v', 'display': '佷'},
            {'target': 'c', 'display': '侀'},
            {'target': 'c', 'display': '侁'},
            {'target': 'c', 'display': '侂'},
            {'target': 'c', 'display': '侃'},
            {'target': 'c', 'display': '侄'},
            {'target': 'c', 'display': '侅'},
            {'target': 'x', 'display': '侐'},
            {'target': 'x', 'display': '侑'},
            {'target': 'x', 'display': '侒'},
            {'target': 'x', 'display': '侓'},
            {'target': 'x', 'display': '侔'},
            {'target': 'x', 'display': '侕'},
            {'target': 'x', 'display': '侖'},
            {'target': 'x', 'display': '侗'},
        ]
    },
    {
        "name": "一级简码",
        "maxTime": 120,
        "condition": 1.1,
        "data": [
            {"display": "一"},
            {"display": "地"},
            {"display": "在"},
            {"display": "要"},
            {"display": "工"},
            {"display": "上"},
            {"display": "是"},
            {"display": "中"},
            {"display": "国"},
            {"display": "同"},
            {"display": "和"},
            {"display": "的"},
            {"display": "有"},
            {"display": "人"},
            {"display": "我"},
            {"display": "主"},
            {"display": "产"},
            {"display": "不"},
            {"display": "为"},
            {"display": "这"},
            {"display": "民"},
            {"display": "了"},
            {"display": "发"},
            {"display": "以"},
            {"display": "经"}
        ]
    },
    {
        "name": "键名汉字",
        "maxTime": 120,
        "condition": 1.5,
        "data": [
            {"display": "金"},
            {"display": "人"},
            {"display": "月"},
            {"display": "白"},
            {"display": "禾"},
            {"display": "言"},
            {"display": "立"},
            {"display": "水"},
            {"display": "火"},
            {"display": "之"},
            {"display": "工"},
            {"display": "木"},
            {"display": "大"},
            {"display": "土"},
            {"display": "王"},
            {"display": "目"},
            {"display": "日"},
            {"display": "口"},
            {"display": "田"},
            {"display": "山"},
            {"display": "已"},
            {"display": "子"},
            {"display": "女"},
            {"display": "又"},
            {"display": "纟"}
        ]
    },
    {
        "name": "二级简码",
        "maxTime": 120,
        "condition": 1.5,
        "data": [
            {"display": "开"},
            {"display": "屯"},
            {"display": "到"},
            {"display": "天"},
            {"display": "表"},
            {"display": "于"},
            {"display": "五"},
            {"display": "下"},
            {"display": "不"},
            {"display": "理"},
            {"display": "事"},
            {"display": "画"},
            {"display": "现"},
            {"display": "与"},
            {"display": "来"},
            {"display": "列"},
            {"display": "珠"},
            {"display": "末"},
            {"display": "玫"},
            {"display": "平"},
            {"display": "妻"},
            {"display": "珍"},
            {"display": "互"},
            {"display": "玉"},
            {"display": "载"},
            {"display": "地"},
            {"display": "支"},
            {"display": "城"},
            {"display": "圾"},
            {"display": "寺"},
            {"display": "二"},
            {"display": "直"},
            {"display": "示"},
            {"display": "进"},
            {"display": "吉"},
            {"display": "协"},
            {"display": "南"},
            {"display": "志"},
            {"display": "赤"},
            {"display": "过"},
            {"display": "无"},
            {"display": "垢"},
            {"display": "霜"},
            {"display": "才"},
            {"display": "增"},
            {"display": "雪"},
            {"display": "夫"},
            {"display": "坟"},
            {"display": "左"},
            {"display": "顾"},
            {"display": "友"},
            {"display": "大"},
            {"display": "胡"},
            {"display": "夺"},
            {"display": "三"},
            {"display": "丰"},
            {"display": "砂"},
            {"display": "百"},
            {"display": "右"},
            {"display": "历"},
            {"display": "面"},
            {"display": "成"},
            {"display": "灰"},
            {"display": "达"},
            {"display": "克"},
            {"display": "原"},
            {"display": "厅"},
            {"display": "帮"},
            {"display": "磁"},
            {"display": "肆"},
            {"display": "春"},
            {"display": "龙"},
            {"display": "太"},
            {"display": "械"},
            {"display": "李"},
            {"display": "权"},
            {"display": "枯"},
            {"display": "极"},
            {"display": "村"},
            {"display": "本"},
            {"display": "相"},
            {"display": "档"},
            {"display": "查"},
            {"display": "可"},
            {"display": "楞"},
            {"display": "机"},
            {"display": "杨"},
            {"display": "杰"},
            {"display": "棕"},
            {"display": "构"},
            {"display": "析"},
            {"display": "林"},
            {"display": "格"},
            {"display": "样"},
            {"display": "要"},
            {"display": "检"},
            {"display": "楷"},
            {"display": "术"},
            {"display": "式"},
            {"display": "节"},
            {"display": "芭"},
            {"display": "基"},
            {"display": "菜"},
            {"display": "革"},
            {"display": "七"},
            {"display": "牙"},
            {"display": "东"},
            {"display": "划"},
            {"display": "或"},
            {"display": "功"},
            {"display": "贡"},
            {"display": "世"},
            {"display": "芝"},
            {"display": "区"},
            {"display": "匠"},
            {"display": "苛"},
            {"display": "攻"},
            {"display": "燕"},
            {"display": "切"},
            {"display": "共"},
            {"display": "药"},
            {"display": "芳"},
            {"display": "虎"},
            {"display": "皮"},
            {"display": "睚"},
            {"display": "肯"},
            {"display": "睦"},
            {"display": "睛"},
            {"display": "止"},
            {"display": "步"},
            {"display": "旧"},
            {"display": "占"},
            {"display": "卤"},
            {"display": "贞"},
            {"display": "卢"},
            {"display": "眯"},
            {"display": "瞎"},
            {"display": "餐"},
            {"display": "睥"},
            {"display": "盯"},
            {"display": "睡"},
            {"display": "瞳"},
            {"display": "眼"},
            {"display": "具"},
            {"display": "此"},
            {"display": "眩"},
            {"display": "虹"},
            {"display": "最"},
            {"display": "紧"},
            {"display": "晨"},
            {"display": "明"},
            {"display": "时"},
            {"display": "量"},
            {"display": "早"},
            {"display": "晃"},
            {"display": "昌"},
            {"display": "蝇"},
            {"display": "曙"},
            {"display": "遇"},
            {"display": "电"},
            {"display": "显"},
            {"display": "晕"},
            {"display": "晚"},
            {"display": "蝗"},
            {"display": "果"},
            {"display": "昨"},
            {"display": "暗"},
            {"display": "归"},
            {"display": "蛤"},
            {"display": "昆"},
            {"display": "景"},
            {"display": "呀"},
            {"display": "啊"},
            {"display": "吧"},
            {"display": "顺"},
            {"display": "吸"},
            {"display": "叶"},
            {"display": "呈"},
            {"display": "中"},
            {"display": "吵"},
            {"display": "虽"},
            {"display": "吕"},
            {"display": "另"},
            {"display": "员"},
            {"display": "叫"},
            {"display": "喧"},
            {"display": "史"},
            {"display": "听"},
            {"display": "呆"},
            {"display": "呼"},
            {"display": "啼"},
            {"display": "哪"},
            {"display": "只"},
            {"display": "哟"},
            {"display": "嘛"},
            {"display": "囝"},
            {"display": "轻"},
            {"display": "因"},
            {"display": "胃"},
            {"display": "轩"},
            {"display": "车"},
            {"display": "四"},
            {"display": "辊"},
            {"display": "加"},
            {"display": "男"},
            {"display": "轴"},
            {"display": "思"},
            {"display": "辚"},
            {"display": "边"},
            {"display": "罗"},
            {"display": "斩"},
            {"display": "困"},
            {"display": "力"},
            {"display": "较"},
            {"display": "轨"},
            {"display": "办"},
            {"display": "累"},
            {"display": "罚"},
            {"display": "曲"},
            {"display": "邮"},
            {"display": "凤"},
            {"display": "央"},
            {"display": "骨"},
            {"display": "财"},
            {"display": "同"},
            {"display": "由"},
            {"display": "峭"},
            {"display": "则"},
            {"display": "崭"},
            {"display": "册"},
            {"display": "岂"},
            {"display": "迪"},
            {"display": "风"},
            {"display": "贩"},
            {"display": "朵"},
            {"display": "几"},
            {"display": "赠"},
            {"display": "内"},
            {"display": "嶷"},
            {"display": "凡"},
            {"display": "长"},
            {"display": "季"},
            {"display": "么"},
            {"display": "知"},
            {"display": "秀"},
            {"display": "行"},
            {"display": "生"},
            {"display": "处"},
            {"display": "秒"},
            {"display": "得"},
            {"display": "各"},
            {"display": "务"},
            {"display": "向"},
            {"display": "秘"},
            {"display": "秋"},
            {"display": "管"},
            {"display": "称"},
            {"display": "物"},
            {"display": "条"},
            {"display": "笔"},
            {"display": "科"},
            {"display": "委"},
            {"display": "答"},
            {"display": "第"},
            {"display": "入"},
            {"display": "找"},
            {"display": "报"},
            {"display": "反"},
            {"display": "拓"},
            {"display": "扔"},
            {"display": "持"},
            {"display": "后"},
            {"display": "年"},
            {"display": "朱"},
            {"display": "提"},
            {"display": "扣"},
            {"display": "押"},
            {"display": "抽"},
            {"display": "所"},
            {"display": "搂"},
            {"display": "近"},
            {"display": "换"},
            {"display": "折"},
            {"display": "打"},
            {"display": "手"},
            {"display": "拉"},
            {"display": "扫"},
            {"display": "失"},
            {"display": "批"},
            {"display": "扩"},
            {"display": "肛"},
            {"display": "服"},
            {"display": "肥"},
            {"display": "须"},
            {"display": "朋"},
            {"display": "肝"},
            {"display": "且"},
            {"display": "膛"},
            {"display": "胆"},
            {"display": "肿"},
            {"display": "肋"},
            {"display": "肌"},
            {"display": "甩"},
            {"display": "爱"},
            {"display": "胸"},
            {"display": "遥"},
            {"display": "采"},
            {"display": "用"},
            {"display": "胶"},
            {"display": "妥"},
            {"display": "脸"},
            {"display": "脂"},
            {"display": "及"},
            {"display": "代"},
            {"display": "他"},
            {"display": "公"},
            {"display": "估"},
            {"display": "仍"},
            {"display": "会"},
            {"display": "全"},
            {"display": "个"},
            {"display": "偿"},
            {"display": "介"},
            {"display": "保"},
            {"display": "佃"},
            {"display": "仙"},
            {"display": "亿"},
            {"display": "伙"},
            {"display": "你"},
            {"display": "伯"},
            {"display": "休"},
            {"display": "作"},
            {"display": "们"},
            {"display": "分"},
            {"display": "从"},
            {"display": "化"},
            {"display": "信"},
            {"display": "氏"},
            {"display": "凶"},
            {"display": "色"},
            {"display": "然"},
            {"display": "角"},
            {"display": "针"},
            {"display": "钱"},
            {"display": "外"},
            {"display": "乐"},
            {"display": "旬"},
            {"display": "名"},
            {"display": "甸"},
            {"display": "负"},
            {"display": "包"},
            {"display": "炙"},
            {"display": "锭"},
            {"display": "多"},
            {"display": "铁"},
            {"display": "钉"},
            {"display": "儿"},
            {"display": "匀"},
            {"display": "争"},
            {"display": "欠"},
            {"display": "久"},
            {"display": "度"},
            {"display": "离"},
            {"display": "充"},
            {"display": "庆"},
            {"display": "衣"},
            {"display": "计"},
            {"display": "主"},
            {"display": "让"},
            {"display": "就"},
            {"display": "是"},
            {"display": "训"},
            {"display": "为"},
            {"display": "高"},
            {"display": "记"},
            {"display": "变"},
            {"display": "这"},
            {"display": "义"},
            {"display": "诉"},
            {"display": "订"},
            {"display": "放"},
            {"display": "说"},
            {"display": "良"},
            {"display": "认"},
            {"display": "率"},
            {"display": "方"},
            {"display": "并"},
            {"display": "闻"},
            {"display": "冯"},
            {"display": "关"},
            {"display": "前"},
            {"display": "半"},
            {"display": "闰"},
            {"display": "站"},
            {"display": "冰"},
            {"display": "间"},
            {"display": "部"},
            {"display": "曾"},
            {"display": "商"},
            {"display": "决"},
            {"display": "普"},
            {"display": "帝"},
            {"display": "交"},
            {"display": "瓣"},
            {"display": "亲"},
            {"display": "产"},
            {"display": "立"},
            {"display": "妆"},
            {"display": "闪"},
            {"display": "北"},
            {"display": "六"},
            {"display": "江"},
            {"display": "池"},
            {"display": "汉"},
            {"display": "尖"},
            {"display": "肖"},
            {"display": "法"},
            {"display": "汪"},
            {"display": "小"},
            {"display": "水"},
            {"display": "浊"},
            {"display": "澡"},
            {"display": "渐"},
            {"display": "没"},
            {"display": "沁"},
            {"display": "淡"},
            {"display": "学"},
            {"display": "光"},
            {"display": "泊"},
            {"display": "洒"},
            {"display": "少"},
            {"display": "洋"},
            {"display": "当"},
            {"display": "兴"},
            {"display": "涨"},
            {"display": "注"},
            {"display": "煤"},
            {"display": "籽"},
            {"display": "烃"},
            {"display": "类"},
            {"display": "粗"},
            {"display": "灶"},
            {"display": "业"},
            {"display": "粘"},
            {"display": "炒"},
            {"display": "烛"},
            {"display": "炽"},
            {"display": "烟"},
            {"display": "灿"},
            {"display": "断"},
            {"display": "炎"},
            {"display": "迷"},
            {"display": "炮"},
            {"display": "煌"},
            {"display": "灯"},
            {"display": "烽"},
            {"display": "料"},
            {"display": "娄"},
            {"display": "粉"},
            {"display": "糨"},
            {"display": "米"},
            {"display": "宽"},
            {"display": "字"},
            {"display": "害"},
            {"display": "家"},
            {"display": "守"},
            {"display": "定"},
            {"display": "寂"},
            {"display": "宵"},
            {"display": "审"},
            {"display": "宫"},
            {"display": "军"},
            {"display": "宙"},
            {"display": "官"},
            {"display": "灾"},
            {"display": "之"},
            {"display": "宛"},
            {"display": "宾"},
            {"display": "宁"},
            {"display": "客"},
            {"display": "实"},
            {"display": "安"},
            {"display": "空"},
            {"display": "它"},
            {"display": "社"},
            {"display": "民"},
            {"display": "敢"},
            {"display": "怪"},
            {"display": "居"},
            {"display": "导"},
            {"display": "怀"},
            {"display": "收"},
            {"display": "悄"},
            {"display": "慢"},
            {"display": "避"},
            {"display": "惭"},
            {"display": "届"},
            {"display": "忆"},
            {"display": "屡"},
            {"display": "忱"},
            {"display": "懈"},
            {"display": "怕"},
            {"display": "必"},
            {"display": "习"},
            {"display": "恨"},
            {"display": "愉"},
            {"display": "尼"},
            {"display": "心"},
            {"display": "陈"},
            {"display": "子"},
            {"display": "取"},
            {"display": "承"},
            {"display": "阴"},
            {"display": "际"},
            {"display": "卫"},
            {"display": "耻"},
            {"display": "孙"},
            {"display": "阳"},
            {"display": "职"},
            {"display": "阵"},
            {"display": "出"},
            {"display": "也"},
            {"display": "耿"},
            {"display": "辽"},
            {"display": "隐"},
            {"display": "孤"},
            {"display": "阿"},
            {"display": "降"},
            {"display": "联"},
            {"display": "限"},
            {"display": "队"},
            {"display": "陛"},
            {"display": "防"},
            {"display": "毁"},
            {"display": "好"},
            {"display": "妈"},
            {"display": "姑"},
            {"display": "奶"},
            {"display": "寻"},
            {"display": "姨"},
            {"display": "录"},
            {"display": "旭"},
            {"display": "如"},
            {"display": "舅"},
            {"display": "妯"},
            {"display": "刀"},
            {"display": "灵"},
            {"display": "巡"},
            {"display": "婚"},
            {"display": "杂"},
            {"display": "九"},
            {"display": "嫌"},
            {"display": "妇"},
            {"display": "姆"},
            {"display": "妨"},
            {"display": "戏"},
            {"display": "邓"},
            {"display": "双"},
            {"display": "参"},
            {"display": "能"},
            {"display": "对"},
            {"display": "骊"},
            {"display": "骒"},
            {"display": "台"},
            {"display": "劝"},
            {"display": "观"},
            {"display": "马"},
            {"display": "驼"},
            {"display": "允"},
            {"display": "牟"},
            {"display": "骠"},
            {"display": "矣"},
            {"display": "艰"},
            {"display": "难"},
            {"display": "驻"},
            {"display": "红"},
            {"display": "弛"},
            {"display": "经"},
            {"display": "顷"},
            {"display": "级"},
            {"display": "结"},
            {"display": "线"},
            {"display": "引"},
            {"display": "纱"},
            {"display": "旨"},
            {"display": "强"},
            {"display": "细"},
            {"display": "纲"},
            {"display": "纪"},
            {"display": "继"},
            {"display": "综"},
            {"display": "约"},
            {"display": "绵"},
            {"display": "张"},
            {"display": "弱"},
            {"display": "绿"},
            {"display": "给"},
            {"display": "比"},
            {"display": "纺"}
        ]
    },
    {
        "name": "三级简码",
        "maxTime": 120,
        "condition": 1.8,
        "data": [
            {"display": "而"},
            {"display": "自"},
            {"display": "着"},
            {"display": "还"},
            {"display": "其"},
            {"display": "起"},
            {"display": "动"},
            {"display": "点"},
            {"display": "问"},
            {"display": "里"},
            {"display": "去"},
            {"display": "将"},
            {"display": "些"},
            {"display": "看"},
            {"display": "十"},
            {"display": "意"},
            {"display": "正"},
            {"display": "想"},
            {"display": "把"},
            {"display": "情"},
            {"display": "者"},
            {"display": "重"},
            {"display": "那"},
            {"display": "应"},
            {"display": "又"},
            {"display": "但"},
            {"display": "种"},
            {"display": "见"},
            {"display": "门"},
            {"display": "先"},
            {"display": "位"},
            {"display": "头"},
            {"display": "回"},
            {"display": "话"},
            {"display": "很"},
            {"display": "再"},
            {"display": "身"},
            {"display": "次"},
            {"display": "别"},
            {"display": "月"},
            {"display": "真"},
            {"display": "新"},
            {"display": "通"},
            {"display": "何"},
            {"display": "接"},
            {"display": "声"},
            {"display": "体"},
            {"display": "合"},
            {"display": "性"},
            {"display": "做"},
            {"display": "己"},
            {"display": "老"},
            {"display": "件"},
            {"display": "解"},
            {"display": "路"},
            {"display": "更"},
            {"display": "走"},
            {"display": "总"},
            {"display": "任"},
            {"display": "便"},
            {"display": "至"},
            {"display": "气"},
            {"display": "神"},
            {"display": "山"},
            {"display": "数"},
            {"display": "利"},
            {"display": "书"},
            {"display": "受"},
            {"display": "非"},
            {"display": "求"},
            {"display": "万"},
            {"display": "算"},
            {"display": "王"},
            {"display": "什"},
            {"display": "快"},
            {"display": "许"},
            {"display": "连"},
            {"display": "活"},
            {"display": "海"},
            {"display": "指"},
            {"display": "连"},
            {"display": "活"},
            {"display": "海"},
            {"display": "指"},
            {"display": "女"},
            {"display": "完"},
            {"display": "言"},
            {"display": "特"},
            {"display": "清"},
            {"display": "带"},
            {"display": "转"},
            {"display": "白"},
            {"display": "像"},
            {"display": "象"},
            {"display": "却"},
            {"display": "流"},
            {"display": "即"},
            {"display": "深"},
            {"display": "形"},
            {"display": "往"},
            {"display": "系"},
            {"display": "论"},
            {"display": "息"},
            {"display": "未"},
            {"display": "花"},
            {"display": "每"},
            {"display": "华"},
            {"display": "远"},
            {"display": "师"},
            {"display": "元"},
            {"display": "请"},
            {"display": "容"},
            {"display": "她"},
            {"display": "语"},
            {"display": "识"},
            {"display": "战"},
            {"display": "院"},
            {"display": "候"},
            {"display": "音"},
            {"display": "死"},
            {"display": "视"},
            {"display": "司"},
            {"display": "始"},
            {"display": "令"},
            {"display": "改"},
            {"display": "德"},
            {"display": "复"},
            {"display": "随"},
            {"display": "青"},
            {"display": "足"},
            {"display": "落"},
            {"display": "根"},
            {"display": "精"},
            {"display": "送"},
            {"display": "众"},
            {"display": "八"},
            {"display": "首"},
            {"display": "准"},
            {"display": "尽"},
            {"display": "故"},
            {"display": "火"},
            {"display": "似"},
            {"display": "备"},
            {"display": "调"},
            {"display": "设"},
            {"display": "消"},
            {"display": "布"},
            {"display": "展"},
            {"display": "据"},
            {"display": "终"},
            {"display": "周"},
            {"display": "举"},
            {"display": "飞"},
            {"display": "片"},
            {"display": "易"},
            {"display": "运"},
            {"display": "笑"},
            {"display": "云"},
            {"display": "谈"},
            {"display": "界"},
            {"display": "写"},
            {"display": "越"},
            {"display": "千"},
            {"display": "微"},
            {"display": "若"},
            {"display": "英"},
            {"display": "集"},
            {"display": "呢"},
            {"display": "坐"},
            {"display": "议"},
            {"display": "乎"},
            {"display": "品"},
            {"display": "黑"},
            {"display": "存"},
            {"display": "低"},
            {"display": "刻"},
            {"display": "尔"},
            {"display": "吃"},
            {"display": "依"},
            {"display": "图"},
            {"display": "咯"},
            {"display": "底"},
            {"display": "装"},
            {"display": "喜"},
            {"display": "严"},
            {"display": "况"},
            {"display": "跟"},
            {"display": "病"},
            {"display": "证"},
            {"display": "刚"},
            {"display": "治"},
            {"display": "绝"},
            {"display": "群"},
            {"display": "确"},
            {"display": "究"},
            {"display": "除"},
            {"display": "段"},
            {"display": "政"},
            {"display": "黄"},
            {"display": "武"},
            {"display": "费"},
            {"display": "㐴"},
            {"display": "统"},
            {"display": "府"},
            {"display": "敬"},
            {"display": "泉"},
            {"display": "残"},
            {"display": "努"},
            {"display": "销"},
            {"display": "稳"},
            {"display": "健"},
            {"display": "锋"},
            {"display": "奖"},
            {"display": "瓦"},
            {"display": "延"},
            {"display": "页"},
            {"display": "冒"},
            {"display": "麦"},
            {"display": "振"},
            {"display": "络"},
            {"display": "剑"},
            {"display": "寒"},
            {"display": "吐"},
            {"display": "滑"},
            {"display": "扎"},
            {"display": "措"},
            {"display": "款"},
            {"display": "泛"},
            {"display": "洲"},
            {"display": "控"},
            {"display": "浮"},
            {"display": "腿"},
            {"display": "均"},
            {"display": "鸣"},
            {"display": "殊"},
            {"display": "腰"},
            {"display": "烦"},
            {"display": "莲"},
            {"display": "惠"},
            {"display": "阶"},
            {"display": "穷"},
            {"display": "抢"},
            {"display": "桌"},
            {"display": "混"},
            {"display": "瓶"},
            {"display": "灭"},
            {"display": "滥"},
            {"display": "用"},
            {"display": "捕"},
            {"display": "佩"},
            {"display": "镜"},
            {"display": "促"},
            {"display": "序"},
            {"display": "劲"},
            {"display": "抵"},
            {"display": "麻"},
            {"display": "骑"},
            {"display": "俱"},
            {"display": "倍"},
            {"display": "瑞"},
            {"display": "伴"},
            {"display": "刺"},
            {"display": "枪"},
            {"display": "拥"},
            {"display": "杯"},
            {"display": "洪"},
            {"display": "扑"},
            {"display": "厂"},
            {"display": "舍"},
            {"display": "陪"},
            {"display": "秦"},
            {"display": "沈"},
            {"display": "迅"},
            {"display": "幽"},
            {"display": "伟"},
            {"display": "涉"},
            {"display": "尾"},
            {"display": "井"},
            {"display": "啦"},
            {"display": "裁"},
            {"display": "咱"},
            {"display": "抬"},
            {"display": "映"},
            {"display": "县"},
            {"display": "航"},
            {"display": "傅"},
            {"display": "唤"},
            {"display": "厚"},
            {"display": "扰"},
            {"display": "疾"},
            {"display": "闭"},
            {"display": "董"},
            {"display": "旋"},
            {"display": "撞"},
            {"display": "诺"},
            {"display": "渡"},
            {"display": "瞧"},
            {"display": "冶"},
            {"display": "兼"},
            {"display": "享"},
            {"display": "奋"},
            {"display": "鸡"},
            {"display": "羊"},
            {"display": "乃"},
            {"display": "紫"},
            {"display": "侯"},
            {"display": "懂"},
            {"display": "稍"},
            {"display": "尺"},
            {"display": "甘"},
            {"display": "亲"},
            {"display": "寿"},
            {"display": "覆"},
            {"display": "尊"},
            {"display": "诸"},
            {"display": "冬"},
            {"display": "侧"},
            {"display": "宇"},
            {"display": "洛"},
            {"display": "测"},
            {"display": "勒"},
            {"display": "罢"},
            {"display": "糊"},
            {"display": "鬼"},
            {"display": "插"},
            {"display": "焦"},
            {"display": "蒙"},
            {"display": "敌"},
            {"display": "透"},
            {"display": "纷"},
            {"display": "丢"},
            {"display": "泽"},
            {"display": "培"},
            {"display": "染"},
            {"display": "臣"},
            {"display": "挤"},
            {"display": "颗"},
            {"display": "搞"},
            {"display": "召"},
            {"display": "缘"},
            {"display": "洁"},
            {"display": "踪"},
            {"display": "纯"},
            {"display": "侵"},
            {"display": "尝"},
            {"display": "固"},
            {"display": "彼"},
            {"display": "乔"},
            {"display": "叔"},
            {"display": "绍"},
            {"display": "记"},
            {"display": "尤"},
            {"display": "旦"},
            {"display": "污"},
            {"display": "慧"},
            {"display": "课"},
            {"display": "钢"},
            {"display": "慰"},
            {"display": "陷"},
            {"display": "暴"},
            {"display": "诚"},
            {"display": "薄"},
            {"display": "震"},
            {"display": "鲜"},
            {"display": "祥"},
            {"display": "绪"},
            {"display": "柳"},
            {"display": "纵"},
            {"display": "迫"},
            {"display": "偶"},
            {"display": "迟"},
            {"display": "绕"},
            {"display": "圈"},
            {"display": "坦"},
            {"display": "距"},
            {"display": "奔"},
            {"display": "皇"},
            {"display": "潍"},
            {"display": "涌"},
            {"display": "闹"},
            {"display": "输"},
            {"display": "溱"},
            {"display": "博"},
            {"display": "补"},
            {"display": "横"},
            {"display": "峰"},
            {"display": "皆"},
            {"display": "狗"},
            {"display": "拖"},
            {"display": "询"},
            {"display": "予"},
            {"display": "怨"},
            {"display": "拔"},
            {"display": "幅"},
            {"display": "枝"},
            {"display": "沿"},
            {"display": "隆"},
            {"display": "挑"},
            {"display": "祝"},
            {"display": "筑"},
            {"display": "伍"},
            {"display": "凝"},
            {"display": "扶"},
            {"display": "屈"},
            {"display": "悉"},
            {"display": "森"},
            {"display": "汤"},
            {"display": "括"},
            {"display": "琴"},
            {"display": "箱"},
            {"display": "壮"},
            {"display": "鱼"},
            {"display": "码"},
            {"display": "惯"},
            {"display": "杜"},
            {"display": "荡"},
            {"display": "聚"},
            {"display": "蛋"},
            {"display": "碎"},
            {"display": "饮"},
            {"display": "定"},
            {"display": "慧"},
            {"display": "桥"},
            {"display": "北"},
            {"display": "隔"},
            {"display": "锦"},
            {"display": "述"},
            {"display": "鼻"},
            {"display": "贫"},
            {"display": "丹"},
            {"display": "宋"},
            {"display": "货"},
            {"display": "番"},
            {"display": "仪"},
            {"display": "欣"},
            {"display": "伏"},
            {"display": "恢"},
            {"display": "唱"},
            {"display": "乌"},
            {"display": "萨"},
            {"display": "孔"},
            {"display": "宜"},
            {"display": "醉"},
            {"display": "符"},
            {"display": "朗"},
            {"display": "爷"},
            {"display": "鲁"},
            {"display": "拒"},
            {"display": "净"},
            {"display": "邦"},
            {"display": "减"},
            {"display": "倾"},
            {"display": "碰"},
            {"display": "狂"},
            {"display": "堆"},
            {"display": "凌"},
            {"display": "竹"},
            {"display": "郑"},
            {"display": "伦"},
            {"display": "妙"},
            {"display": "奈"},
            {"display": "忧"},
            {"display": "徐"},
            {"display": "铺"},
            {"display": "吹"},
            {"display": "描"},
            {"display": "俊"},
            {"display": "贯"},
            {"display": "企"},
            {"display": "匆"},
            {"display": "授"},
            {"display": "典"},
            {"display": "怒"},
            {"display": "剧"},
            {"display": "旗"},
            {"display": "叹"},
            {"display": "锁"},
            {"display": "详"},
            {"display": "陆"},
            {"display": "卡"},
            {"display": "巨"},
            {"display": "泥"},
            {"display": "返"},
            {"display": "途"},
            {"display": "截"},
            {"display": "匹"},
            {"display": "损"},
            {"display": "申"},
            {"display": "启"},
            {"display": "陶"},
            {"display": "谋"},
            {"display": "蓝"},
            {"display": "滚"},
            {"display": "浓"},
            {"display": "融"},
            {"display": "泪"},
            {"display": "弃"},
            {"display": "孟"},
            {"display": "颇"},
            {"display": "吴"},
            {"display": "谷"},
            {"display": "奥"},
            {"display": "魂"},
            {"display": "仿"},
            {"display": "径"},
            {"display": "妹"},
            {"display": "忠"},
            {"display": "缩"},
            {"display": "伊"},
            {"display": "烧"},
            {"display": "跨"},
            {"display": "丧"},
            {"display": "肃"},
            {"display": "垂"},
            {"display": "择"},
            {"display": "厉"},
            {"display": "暂"},
            {"display": "丈"},
            {"display": "讯"},
            {"display": "迹"},
            {"display": "辆"},
            {"display": "帐"},
            {"display": "奉"},
            {"display": "库"},
            {"display": "逃"},
            {"display": "洗"},
            {"display": "弹"},
            {"display": "附"},
            {"display": "尘"},
            {"display": "赵"},
            {"display": "腾"},
            {"display": "桥"},
            {"display": "评"},
            {"display": "亏"},
            {"display": "弄"},
            {"display": "田"},
            {"display": "压"},
            {"display": "逐"},
            {"display": "席"},
            {"display": "积"},
            {"display": "苦"},
            {"display": "退"},
            {"display": "范"},
            {"display": "趣"},
            {"display": "坏"},
            {"display": "顶"},
            {"display": "楚"},
            {"display": "跳"},
            {"display": "乱"},
            {"display": "油"},
            {"display": "付"},
            {"display": "移"},
            {"display": "喝"},
            {"display": "姐"},
            {"display": "湖"},
            {"display": "维"},
            {"display": "遍"},
            {"display": "停"},
            {"display": "网"},
            {"display": "挥"},
            {"display": "宣"},
            {"display": "古"},
            {"display": "险"},
            {"display": "伤"},
            {"display": "讨"},
            {"display": "竟"},
            {"display": "案"},
            {"display": "祖"},
            {"display": "香"},
            {"display": "投"},
            {"display": "劳"},
            {"display": "室"},
            {"display": "屋"},
            {"display": "济"},
            {"display": "园"},
            {"display": "征"},
            {"display": "圣"},
            {"display": "软"},
            {"display": "荣"},
            {"display": "般"},
            {"display": "罪"},
            {"display": "略"},
            {"display": "杀"},
            {"display": "局"},
            {"display": "模"},
            {"display": "虑"},
            {"display": "拍"},
            {"display": "犯"},
            {"display": "营"},
            {"display": "野"},
            {"display": "威"},
            {"display": "省"},
            {"display": "仁"},
            {"display": "研"},
            {"display": "亦"},
            {"display": "某"},
            {"display": "需"},
            {"display": "按"},
            {"display": "突"},
            {"display": "树"},
            {"display": "排"},
            {"display": "佛"},
            {"display": "属"},
            {"display": "素"},
            {"display": "岁"},
            {"display": "虚"},
            {"display": "担"},
            {"display": "板"},
            {"display": "号"},
            {"display": "党"},
            {"display": "短"},
            {"display": "松"},
            {"display": "醒"},
            {"display": "脱"},
            {"display": "轮"},
            {"display": "唐"},
            {"display": "迎"},
            {"display": "舞"},
            {"display": "组"},
            {"display": "坚"},
            {"display": "娘"},
            {"display": "访"},
            {"display": "股"},
            {"display": "脑"},
            {"display": "效"},
            {"display": "配"},
            {"display": "考"},
            {"display": "农"},
            {"display": "毫"},
            {"display": "托"},
            {"display": "斗"},
            {"display": "否"},
            {"display": "食"},
            {"display": "禁"},
            {"display": "耳"},
            {"display": "层"},
            {"display": "乡"},
            {"display": "急"},
            {"display": "康"},
            {"display": "益"},
            {"display": "纳"},
            {"display": "缓"},
            {"display": "欢"},
            {"display": "份"},
            {"display": "句"},
            {"display": "著"},
            {"display": "毛"},
            {"display": "午"},
            {"display": "玩"},
            {"display": "态"},
            {"display": "仅"},
            {"display": "嘴"},
            {"display": "副"},
            {"display": "护"},
            {"display": "密"},
            {"display": "丽"},
            {"display": "肉"},
            {"display": "床"},
            {"display": "缺"},
            {"display": "余"},
            {"display": "雷"},
            {"display": "印"},
            {"display": "激"},
            {"display": "胜"},
            {"display": "熟"},
            {"display": "摆"},
            {"display": "丁"},
            {"display": "创"},
            {"display": "技"},
            {"display": "艺"},
            {"display": "策"},
            {"display": "夜"},
            {"display": "续"},
            {"display": "临"},
            {"display": "温"},
            {"display": "倒"},
            {"display": "座"},
            {"display": "握"},
            {"display": "校"},
            {"display": "免"},
            {"display": "掉"},
            {"display": "痛"},
            {"display": "助"},
            {"display": "亚"},
            {"display": "释"},
            {"display": "味"},
            {"display": "毕"},
            {"display": "替"},
            {"display": "欧"},
            {"display": "冲"},
            {"display": "标"},
            {"display": "错"},
            {"display": "幸"},
            {"display": "跑"},
            {"display": "状"},
            {"display": "星"},
            {"display": "抱"},
            {"display": "初"},
            {"display": "诗"},
            {"display": "茶"},
            {"display": "盘"},
            {"display": "质"},
            {"display": "升"},
            {"display": "静"},
            {"display": "束"},
            {"display": "梦"},
            {"display": "讲"},
            {"display": "班"},
            {"display": "器"},
            {"display": "价"},
            {"display": "派"},
            {"display": "源"},
            {"display": "端"},
            {"display": "晓"},
            {"display": "宝"},
            {"display": "既"},
            {"display": "私"},
            {"display": "硬"},
            {"display": "族"},
            {"display": "牛"},
            {"display": "执"},
            {"display": "境"},
            {"display": "优"},
            {"display": "获"},
            {"display": "庄"},
            {"display": "京"},
            {"display": "索"},
            {"display": "育"},
            {"display": "户"},
            {"display": "沉"},
            {"display": "预"},
            {"display": "窗"},
            {"display": "试"},
            {"display": "散"},
            {"display": "借"},
            {"display": "草"},
            {"display": "败"},
            {"display": "责"},
            {"display": "饭"},
            {"display": "章"},
            {"display": "验"},
            {"display": "楼"},
            {"display": "血"},
            {"display": "浪"},
            {"display": "误"},
            {"display": "苏"},
            {"display": "危"},
            {"display": "伸"},
            {"display": "哥"},
            {"display": "纸"},
            {"display": "医"},
            {"display": "沙"},
            {"display": "独"},
            {"display": "希"},
            {"display": "兵"},
            {"display": "读"},
            {"display": "破"},
            {"display": "招"},
            {"display": "波"},
            {"display": "差"},
            {"display": "规"},
            {"display": "丝"},
            {"display": "齐"},
            {"display": "谢"},
            {"display": "概"},
            {"display": "店"},
            {"display": "河"},
            {"display": "材"},
            {"display": "宗"},
            {"display": "梅"},
            {"display": "击"},
            {"display": "演"},
            {"display": "姓"},
            {"display": "套"},
            {"display": "弟"},
            {"display": "忽"},
            {"display": "环"},
            {"display": "环"},
            {"display": "项"},
            {"display": "超"},
            {"display": "团"},
            {"display": "永"},
            {"display": "适"},
            {"display": "朝"},
            {"display": "雄"},
            {"display": "馆"},
            {"display": "块"},
            {"display": "银"},
            {"display": "背"},
            {"display": "修"},
            {"display": "施"},
            {"display": "恩"},
            {"display": "兰"},
            {"display": "莫"},
            {"display": "供"},
            {"display": "例"},
            {"display": "架"},
            {"display": "球"},
            {"display": "异"},
            {"display": "夏"},
            {"display": "练"},
            {"display": "摇"},
            {"display": "母"},
            {"display": "兄"},
            {"display": "谓"},
            {"display": "哈"},
            {"display": "操"},
            {"display": "扬"},
            {"display": "吗"},
            {"display": "旁"},
            {"display": "彩"},
            {"display": "织"},
            {"display": "富"},
            {"display": "专"},
            {"display": "福"},
            {"display": "亮"},
            {"display": "勇"},
            {"display": "巴"}
        ]
    }
]
